# Generated by Django 4.0.4 on 2022-05-31 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content1',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='title1',
            new_name='title',
        ),
    ]
